  GNU nano 5.6.1                                                                                                 docker-compose.yml                                                                                                           
version: "3.9"

services:
  certbot-he:
    image: certbot/certbot:latest
    container_name: certbot-he
    volumes:
      - ./certbot-data/letsencrypt:/etc/letsencrypt
      - ./certbot-data/dns_he_ddns.ini:/dns_he_ddns.ini:ro
      - ./hooks/deploy-hook.sh:/deploy-hook.sh:ro
      - ./node-deploy:/node-deploy:ro
      - ./env.certbot:/env.certbot:ro
      - ./env.nodes:/env.nodes:ro
      - /home/certmaster/.ssh:/home/certmaster/.ssh:ro
    entrypoint: sh
    command: -c "sleep infinity"
